// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/todos.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Todo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Completed     bool                   `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Todo) Reset() {
	*x = Todo{}
	mi := &file_proto_todos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Todo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Todo) ProtoMessage() {}

func (x *Todo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Todo.ProtoReflect.Descriptor instead.
func (*Todo) Descriptor() ([]byte, []int) {
	return file_proto_todos_proto_rawDescGZIP(), []int{0}
}

func (x *Todo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Todo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Todo) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

type CreateOneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOneRequest) Reset() {
	*x = CreateOneRequest{}
	mi := &file_proto_todos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOneRequest) ProtoMessage() {}

func (x *CreateOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOneRequest.ProtoReflect.Descriptor instead.
func (*CreateOneRequest) Descriptor() ([]byte, []int) {
	return file_proto_todos_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOneRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type GetOneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOneRequest) Reset() {
	*x = GetOneRequest{}
	mi := &file_proto_todos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneRequest) ProtoMessage() {}

func (x *GetOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneRequest.ProtoReflect.Descriptor instead.
func (*GetOneRequest) Descriptor() ([]byte, []int) {
	return file_proto_todos_proto_rawDescGZIP(), []int{2}
}

func (x *GetOneRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetManyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManyRequest) Reset() {
	*x = GetManyRequest{}
	mi := &file_proto_todos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManyRequest) ProtoMessage() {}

func (x *GetManyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManyRequest.ProtoReflect.Descriptor instead.
func (*GetManyRequest) Descriptor() ([]byte, []int) {
	return file_proto_todos_proto_rawDescGZIP(), []int{3}
}

type ManyTodosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Todos         []*Todo                `protobuf:"bytes,1,rep,name=todos,proto3" json:"todos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManyTodosResponse) Reset() {
	*x = ManyTodosResponse{}
	mi := &file_proto_todos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManyTodosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManyTodosResponse) ProtoMessage() {}

func (x *ManyTodosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManyTodosResponse.ProtoReflect.Descriptor instead.
func (*ManyTodosResponse) Descriptor() ([]byte, []int) {
	return file_proto_todos_proto_rawDescGZIP(), []int{4}
}

func (x *ManyTodosResponse) GetTodos() []*Todo {
	if x != nil {
		return x.Todos
	}
	return nil
}

type UpdateOneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Completed     bool                   `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOneRequest) Reset() {
	*x = UpdateOneRequest{}
	mi := &file_proto_todos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOneRequest) ProtoMessage() {}

func (x *UpdateOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOneRequest.ProtoReflect.Descriptor instead.
func (*UpdateOneRequest) Descriptor() ([]byte, []int) {
	return file_proto_todos_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateOneRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateOneRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateOneRequest) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

type DeleteOneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOneResponse) Reset() {
	*x = DeleteOneResponse{}
	mi := &file_proto_todos_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOneResponse) ProtoMessage() {}

func (x *DeleteOneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todos_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOneResponse.ProtoReflect.Descriptor instead.
func (*DeleteOneResponse) Descriptor() ([]byte, []int) {
	return file_proto_todos_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteOneResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_todos_proto protoreflect.FileDescriptor

const file_proto_todos_proto_rawDesc = "" +
	"\n" +
	"\x11proto/todos.proto\x12\x04main\"J\n" +
	"\x04Todo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1c\n" +
	"\tcompleted\x18\x03 \x01(\bR\tcompleted\"(\n" +
	"\x10CreateOneRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\"\x1f\n" +
	"\rGetOneRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x10\n" +
	"\x0eGetManyRequest\"5\n" +
	"\x11ManyTodosResponse\x12 \n" +
	"\x05todos\x18\x01 \x03(\v2\n" +
	".main.TodoR\x05todos\"V\n" +
	"\x10UpdateOneRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1c\n" +
	"\tcompleted\x18\x03 \x01(\bR\tcompleted\"-\n" +
	"\x11DeleteOneResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x89\x02\n" +
	"\x05Todos\x12/\n" +
	"\tCreateOne\x12\x16.main.CreateOneRequest\x1a\n" +
	".main.Todo\x12)\n" +
	"\x06GetOne\x12\x13.main.GetOneRequest\x1a\n" +
	".main.Todo\x128\n" +
	"\aGetMany\x12\x14.main.GetManyRequest\x1a\x17.main.ManyTodosResponse\x12/\n" +
	"\tUpdateOne\x12\x16.main.UpdateOneRequest\x1a\n" +
	".main.Todo\x129\n" +
	"\tDeleteOne\x12\x13.main.GetOneRequest\x1a\x17.main.DeleteOneResponseB\x0eZ\fvideo3/protob\x06proto3"

var (
	file_proto_todos_proto_rawDescOnce sync.Once
	file_proto_todos_proto_rawDescData []byte
)

func file_proto_todos_proto_rawDescGZIP() []byte {
	file_proto_todos_proto_rawDescOnce.Do(func() {
		file_proto_todos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_todos_proto_rawDesc), len(file_proto_todos_proto_rawDesc)))
	})
	return file_proto_todos_proto_rawDescData
}

var file_proto_todos_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_todos_proto_goTypes = []any{
	(*Todo)(nil),              // 0: main.Todo
	(*CreateOneRequest)(nil),  // 1: main.CreateOneRequest
	(*GetOneRequest)(nil),     // 2: main.GetOneRequest
	(*GetManyRequest)(nil),    // 3: main.GetManyRequest
	(*ManyTodosResponse)(nil), // 4: main.ManyTodosResponse
	(*UpdateOneRequest)(nil),  // 5: main.UpdateOneRequest
	(*DeleteOneResponse)(nil), // 6: main.DeleteOneResponse
}
var file_proto_todos_proto_depIdxs = []int32{
	0, // 0: main.ManyTodosResponse.todos:type_name -> main.Todo
	1, // 1: main.Todos.CreateOne:input_type -> main.CreateOneRequest
	2, // 2: main.Todos.GetOne:input_type -> main.GetOneRequest
	3, // 3: main.Todos.GetMany:input_type -> main.GetManyRequest
	5, // 4: main.Todos.UpdateOne:input_type -> main.UpdateOneRequest
	2, // 5: main.Todos.DeleteOne:input_type -> main.GetOneRequest
	0, // 6: main.Todos.CreateOne:output_type -> main.Todo
	0, // 7: main.Todos.GetOne:output_type -> main.Todo
	4, // 8: main.Todos.GetMany:output_type -> main.ManyTodosResponse
	0, // 9: main.Todos.UpdateOne:output_type -> main.Todo
	6, // 10: main.Todos.DeleteOne:output_type -> main.DeleteOneResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_todos_proto_init() }
func file_proto_todos_proto_init() {
	if File_proto_todos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_todos_proto_rawDesc), len(file_proto_todos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_todos_proto_goTypes,
		DependencyIndexes: file_proto_todos_proto_depIdxs,
		MessageInfos:      file_proto_todos_proto_msgTypes,
	}.Build()
	File_proto_todos_proto = out.File
	file_proto_todos_proto_goTypes = nil
	file_proto_todos_proto_depIdxs = nil
}
